name: TeleBot

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.9.12
  - sqlite=3.36.0
  - bs4=4.11.1
  - requests=2.28.1
  - pyyaml=6.0
  - lxml=4.9.1
  - pandas=1.4.3
  - selenium=3.141.0
  - pip
    - python-telegram-bot==20.0a2

